/**
 * `next lint` was removed in Next 16, which left the scaffold's lint script
 * pointing at nothing. eslint-config-next already ships flat config, so ESLint
 * runs directly against it — no compat layer.
 */
import coreWebVitals from 'eslint-config-next/core-web-vitals';
import typescript from 'eslint-config-next/typescript';

const config = [
  { ignores: ['legacy/**', 'out/**', '.next/**'] },
  ...coreWebVitals,
  ...typescript,

  {
    rules: {
      // `images.unoptimized` is forced on by `output: 'export'`, so next/image
      // would add a component and a wrapper element to emit the same <img>.
      // Icons are pre-sized WebP generated by scripts/optimize-icons.mjs.
      '@next/next/no-img-element': 'off',

      // `const { [key]: _removed, ...rest } = record` is how a key is dropped
      // without mutating; the binding exists to be discarded.
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { varsIgnorePattern: '^_', argsIgnorePattern: '^_' },
      ],
    },
  },

  {
    // Config files are anonymous exports by definition.
    files: ['*.config.mjs', '**/*.config.mjs'],
    rules: { 'import/no-anonymous-default-export': 'off' },
  },
];

export default config;
