/**
 * Cuts the shipped web fonts down to the characters this site can render.
 *
 * The upstream Pretendard files carry Cyrillic, Latin Extended, old Hangul
 * jamo and — in the JP build — the full CJK range. Together that is 7.2 MB of
 * font on a site whose entire vocabulary is 806 distinct characters.
 *
 * Sources live in assets/font/ and are never deployed; the subsets land in
 * public/font/ and are committed, like the optimised icons. Re-run this after
 * changing data or messages, then `npm run check:fonts` to confirm coverage.
 *
 * Usage: node scripts/subset-fonts.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import subsetFont from 'subset-font';
import { buildCharsets } from './lib/charset.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE = path.join(ROOT, 'assets', 'font');
const TARGET = path.join(ROOT, 'public', 'font');

// Matches the `font-weight: 45 920` in the @font-face declarations; keeping the
// axis means one file still covers every weight the design uses.
const VARIATION_AXES = { wght: { min: 45, max: 920 } };

const charsets = buildCharsets();

const JOBS = [
  { file: 'PretendardVariable.woff2', chars: charsets.kr, label: '라틴 + 한글' },
  { file: 'PretendardJPVariable.woff2', chars: charsets.jp, label: '가나 + 한자' },
];

const kb = (bytes) => `${(bytes / 1024).toFixed(0)} KB`;

/**
 * Collapses a character set into the shortest equivalent `unicode-range`.
 *
 * This has to be generated rather than hand-written. The Japanese face carries
 * only the ~200 kanji the site renders, scattered across the CJK block; a
 * hand-kept `U+4E00-9FFF` would tell the browser to use a font that cannot
 * draw the character, producing tofu instead of a system fallback.
 */
function unicodeRange(chars) {
  const points = [...chars].map((c) => c.codePointAt(0)).sort((a, b) => a - b);
  const spans = [];

  for (const cp of points) {
    const last = spans.at(-1);
    if (last && cp === last[1] + 1) last[1] = cp;
    else spans.push([cp, cp]);
  }

  const hex = (cp) => cp.toString(16).toUpperCase().padStart(4, '0');
  return spans
    .map(([from, to]) => (from === to ? `U+${hex(from)}` : `U+${hex(from)}-${hex(to)}`))
    .join(', ');
}

fs.mkdirSync(TARGET, { recursive: true });

let before = 0;
let after = 0;
const faces = [];

for (const { file, chars, label } of JOBS) {
  const source = path.join(SOURCE, file);
  if (!fs.existsSync(source)) {
    console.error(`missing source font: ${path.relative(ROOT, source)}`);
    process.exit(1);
  }

  const original = fs.readFileSync(source);
  const subset = await subsetFont(original, [...chars].join(''), {
    targetFormat: 'woff2',
    variationAxes: VARIATION_AXES,
  });

  fs.writeFileSync(path.join(TARGET, file), subset);

  before += original.length;
  after += subset.length;
  faces.push({ file, label, chars });

  const saved = ((1 - subset.length / original.length) * 100).toFixed(1);
  console.log(
    `${file.padEnd(28)} ${label.padEnd(12)} ` +
      `${String(chars.size).padStart(6)}자  ` +
      `${kb(original.length).padStart(8)} -> ${kb(subset.length).padStart(7)}  (-${saved}%)`,
  );
}

/* -- the stylesheet that declares them ------------------------------------- */

const css = `/* Generated by scripts/subset-fonts.mjs — do not edit.
 *
 * The unicode-range values describe exactly what each subset contains. The
 * Japanese face carries only the kanji the site renders, so its range is a list
 * of individual code points rather than the whole CJK block: claiming more than
 * the file holds makes the browser draw tofu instead of falling back.
 *
 * Re-run \`npm run fonts:subset\` after changing data/ or src/messages/.
 */

${faces
  .map(
    ({ file, label, chars }) => `/* ${label} */
@font-face {
  font-family: 'Pretendard Variable';
  font-weight: 45 920;
  font-style: normal;
  font-display: swap;
  src: url('/font/${file}') format('woff2-variations');
  unicode-range: ${unicodeRange(chars)};
}`,
  )
  .join('\n\n')}
`;

const cssPath = path.join(ROOT, 'src', 'app', 'fonts.css');
fs.writeFileSync(cssPath, css, 'utf8');

console.log(
  `\n합계 ${kb(before)} -> ${kb(after)} ` +
    `(-${((1 - after / before) * 100).toFixed(1)}%)`,
);
console.log(`${path.relative(ROOT, cssPath)} 생성 (${kb(Buffer.byteLength(css))})`);
